<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Dashboard.Application\Dashboard.Application.csproj" />
    <ProjectReference Include="..\..\Tracker\Tracker.Infrastructure\Tracker.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Catalog\Catalog.Infrastructure\Catalog.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Investment\Investment.Infrastructure\Investment.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Calendar\Calendar.Infrastructure\Calendar.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Shared\Finox.Shared.Infrastructure\Finox.Shared.Infrastructure.csproj" />
  </ItemGroup>
</Project>
