<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bank.Application\Bank.Application.csproj" />
    <ProjectReference Include="..\Bank.Infrastructure\Bank.Infrastructure.csproj" />
  </ItemGroup>
</Project>
