<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Finox.Shared.Application\Finox.Shared.Application.csproj" />
    <ProjectReference Include="..\Finox.Shared.Infrastructure\Finox.Shared.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
